on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: josephholten/kleardb
      options: --user root

    steps:
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Git Safe
        run: git config --global --add safe.directory /__w/kleardb/kleardb

      - name: Install and configure Dependencies
        run: conan install .
      - name: Build
        run: conan build .
      - name: Test
        run: ./build/Debug/kleardb_test
