on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install conan
        run: pip install -r requirements.txt

      - name: Install and configure Dependencies
        run: conan install . -pr:a .github/conan.profile
      - name: Build
        run: conan build . -pr:a .github/conan.profile
      - name: Test
        run: ./build/Release/kleardb_test
