on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "Conan version ${{ steps.conan.outputs.version }}"
      - name: Configure CMake
        run: conan install .
      - name: Build
        run: conan build -s build_type=Debug .
      - name: Test
        run: ./build/Debug/kleardb_test
