on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ./build
      - name: Build
        run: cmake --build ./build
      - name: Fake Test
        run: ls non_existant_dir
      - name: Test
        run: ./build/kleardb_test
