on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: conanio/gcc11
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Install and configure Dependencies
        run: conan install . --profile .github/conan.profile
      - name: Build
        run: conan build . -s build_type=Debug
      - name: Test
        run: ./build/Debug/kleardb_test
