on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Setup conan
        uses: hankhsu1996/setup-conan@v1
        with:
          cache-dependencies: true
          cache-tool: true

      - name: Install and configure Dependencies
        run: conan install . -pr:a .github/conan.profile --build=missing
      - name: Build
        run: conan build . -pr:a .github/conan.profile
      - name: Test
        run: ./build/Release/kleardb_test
